
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CinemaSoap", targetNamespace = "http://tempuri.org/", wsdlLocation = "https://localhost:44301/CinemaService.svc?wsdl")
public class CinemaSoap
    extends Service
{

    private final static URL CINEMASOAP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.tempuri.CinemaSoap.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.tempuri.CinemaSoap.class.getResource(".");
            url = new URL(baseUrl, "https://localhost:44301/CinemaService.svc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://localhost:44301/CinemaService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CINEMASOAP_WSDL_LOCATION = url;
    }

    public CinemaSoap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CinemaSoap() {
        super(CINEMASOAP_WSDL_LOCATION, new QName("http://tempuri.org/", "CinemaSoap"));
    }

    /**
     * 
     * @return
     *     returns ICinemaService
     */
    @WebEndpoint(name = "WSHttpBinding_ICinemaService")
    public ICinemaService getWSHttpBindingICinemaService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_ICinemaService"), ICinemaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICinemaService
     */
    @WebEndpoint(name = "WSHttpBinding_ICinemaService")
    public ICinemaService getWSHttpBindingICinemaService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_ICinemaService"), ICinemaService.class, features);
    }

}
