
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.cinemasoap_service.ArrayOfMovie;
import org.datacontract.schemas._2004._07.cinemasoap_service.ArrayOfReservation;
import org.datacontract.schemas._2004._07.cinemasoap_service.ArrayOfSeat;
import org.datacontract.schemas._2004._07.cinemasoap_service.EditReservationRequestDTO;
import org.datacontract.schemas._2004._07.cinemasoap_service.FileContentResponseDTO;
import org.datacontract.schemas._2004._07.cinemasoap_service.User;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ICinemaService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    org.tempuri.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.cinemasoap_service.ObjectFactory.class
})
public interface ICinemaService {


    /**
     * 
     * @param date
     * @return
     *     returns org.datacontract.schemas._2004._07.cinemasoap_service.ArrayOfMovie
     */
    @WebMethod(operationName = "GetRepertoire", action = "http://tempuri.org/ICinemaService/GetRepertoire")
    @WebResult(name = "GetRepertoireResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetRepertoire", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRepertoire")
    @ResponseWrapper(localName = "GetRepertoireResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRepertoireResponse")
    public ArrayOfMovie getRepertoire(
        @WebParam(name = "date", targetNamespace = "http://tempuri.org/")
        String date);

    /**
     * 
     * @param user
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "SignUp", action = "http://tempuri.org/ICinemaService/SignUp")
    @WebResult(name = "SignUpResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SignUp", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SignUp")
    @ResponseWrapper(localName = "SignUpResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SignUpResponse")
    public Boolean signUp(
        @WebParam(name = "user", targetNamespace = "http://tempuri.org/")
        User user);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "CancelReservation", action = "http://tempuri.org/ICinemaService/CancelReservation")
    @WebResult(name = "CancelReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CancelReservation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelReservation")
    @ResponseWrapper(localName = "CancelReservationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelReservationResponse")
    public Boolean cancelReservation(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id);

    /**
     * 
     * @param newReservation
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "EditReservation", action = "http://tempuri.org/ICinemaService/EditReservation")
    @WebResult(name = "EditReservationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "EditReservation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditReservation")
    @ResponseWrapper(localName = "EditReservationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditReservationResponse")
    public Boolean editReservation(
        @WebParam(name = "newReservation", targetNamespace = "http://tempuri.org/")
        EditReservationRequestDTO newReservation);

    /**
     * 
     * @param chosenSeats
     * @param email
     * @param screeningID
     * @return
     *     returns org.datacontract.schemas._2004._07.cinemasoap_service.FileContentResponseDTO
     */
    @WebMethod(operationName = "BookScreening", action = "http://tempuri.org/ICinemaService/BookScreening")
    @WebResult(name = "BookScreeningResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "BookScreening", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookScreening")
    @ResponseWrapper(localName = "BookScreeningResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.BookScreeningResponse")
    public FileContentResponseDTO bookScreening(
        @WebParam(name = "screeningID", targetNamespace = "http://tempuri.org/")
        String screeningID,
        @WebParam(name = "chosenSeats", targetNamespace = "http://tempuri.org/")
        ArrayOfSeat chosenSeats,
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email);

    /**
     * 
     * @param email
     * @return
     *     returns org.datacontract.schemas._2004._07.cinemasoap_service.ArrayOfReservation
     */
    @WebMethod(operationName = "GetReservationList", action = "http://tempuri.org/ICinemaService/GetReservationList")
    @WebResult(name = "GetReservationListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetReservationList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReservationList")
    @ResponseWrapper(localName = "GetReservationListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReservationListResponse")
    public ArrayOfReservation getReservationList(
        @WebParam(name = "email", targetNamespace = "http://tempuri.org/")
        String email);

    /**
     * 
     * @param movieId
     * @return
     *     returns org.datacontract.schemas._2004._07.cinemasoap_service.FileContentResponseDTO
     */
    @WebMethod(operationName = "GetMoviePoster", action = "http://tempuri.org/ICinemaService/GetMoviePoster")
    @WebResult(name = "GetMoviePosterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetMoviePoster", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMoviePoster")
    @ResponseWrapper(localName = "GetMoviePosterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetMoviePosterResponse")
    public FileContentResponseDTO getMoviePoster(
        @WebParam(name = "movieId", targetNamespace = "http://tempuri.org/")
        String movieId);

}
